galacticMotors/core/views.py
from flask import render_template, request, Blueprint, session, redirect, url_for, jsonify
from galacticMotors.models import db, Car, Client

from galacticMotors.core.forms import PurchaseForm
import json
import stripe

# This is your test secret API key.
stripe.api_key = 'sk_test_51P5p6G01NS80YBx34MgQlX1Q8AWKeaXPYldnl1vzzOPo5EP7McyvnmQS7nQ17f6oAZEDXbHlWVhnTHwTZF6rVPD200iPhMUR6q'

# Creates blueprint for core
core = Blueprint('core', __name__)

# Function to load data from CSV, to be called only once
#@app.before_first_request

@core.route('/')
def index():    
    return render_template('index.html')

# Route for displaying all cars without any filters
@core.route('/cars')
def cars():
    page = request.args.get('page', 1, type=int)
    filters = {}
    priceFilters = {}
    # Loads distinct values for all filters
    makes = Car.query.with_entities(Car.make).distinct().all()
    models = Car.query.with_entities(Car.model).distinct().all()
    towns = Car.query.with_entities(Car.town).distinct().all()
    regions = Car.query.with_entities(Car.region).distinct().all()
    # Query to get all cars
    query = Car.query
    cars = query.paginate(page=page, per_page=8)
    return render_template('cars.html', cars=cars, filters=filters, priceFilters=priceFilters, makes=makes, models=models, towns=towns, regions=regions)

# I've tried changing the def name to just filteredCars but it breaks the code for some reason
@core.route('/filtered-cars', methods=['GET', 'POST'])
def filtered_cars():
    page = request.args.get('page', 1, type=int)

    # Defines filters dictionary
    if request.method == 'POST':
        # Updates session with form data for each filter
        session['make'] = request.form.get('make')
        session['model'] = request.form.get('model')
        session['town'] = request.form.get('town')
        session['region'] = request.form.get('region')
        session['minPrice'] = request.form.get('minPrice')
        session['maxPrice'] = request.form.get('maxPrice')

    # Checks for GET request and updates session (for images in index.html)
    if request.method == 'GET':
        session['make'] = request.args.get('make')
        session['model'] = request.args.get('model')

        
    # Loads distinct values for all filters
    makes = Car.query.with_entities(Car.make).distinct().all()
    models = Car.query.with_entities(Car.model).distinct().all()
    towns = Car.query.with_entities(Car.town).distinct().all()
    regions = Car.query.with_entities(Car.region).distinct().all()

    # Retrieves session data to maintain filter state and stores in a dictionary
    filters = {
        'make': session.get('make'),
        'model': session.get('model'),
        'town': session.get('town'),
        'region': session.get('region')
    }
    # Retrieves min and max price from session and stores into a separate dictionary
    priceFilters = {
        'minPrice': session.get('minPrice'),
        'maxPrice': session.get('maxPrice')
    }
    # Builds query based on session filters
    query = Car.query
    for key, value in filters.items():
        if value:
            query = query.filter(getattr(Car, key) == value)    

    # Filters by price range if both min and max prices are provided    
    if priceFilters['minPrice'] and priceFilters['maxPrice']:
        query = query.filter(Car.price.between(priceFilters['minPrice'], priceFilters['maxPrice']))
    elif priceFilters['minPrice']:
        query = query.filter(Car.price >= priceFilters['minPrice'])
    elif priceFilters['maxPrice']:
        query = query.filter(Car.price <= priceFilters['maxPrice'])    

    # Execute the query and paginate results
    cars = query.paginate(page=page, per_page=6)
    return render_template('cars.html', cars=cars, filters=filters, priceFilters=priceFilters, makes=makes, models=models, towns=towns, regions=regions)

# I've tried changing the def name to just clearFilters but it breaks the code for some reason
@core.route('/clear-filters')
def clear_filters():
    # List of filter keys to clear from the session
    filter_keys = ['make', 'model', 'town', 'region', 'colour', 'miles', 'price_min', 'price_max']
    # Clear each filter key from the session
    for key in filter_keys:
        session.pop(key, None)
    # Redirects back to the cars page
    return redirect(url_for('core.cars'))

# I've tried changing the def name to just getModels but it breaks the code for some reason
# Handles AJAX request and returns models for a selected make
@core.route('/get-models/<make>')
def get_models(make):
    models = Car.query.filter_by(make=make).with_entities(Car.model).distinct().all()
    model_list = [model[0] for model in models]  # Converts to a simple list
    return jsonify(model_list)

# I've tried changing the def name to just getTowns but it breaks the code for some reason
# Handles AJAX request and returns towns for a selected model
@core.route('/get-towns/<model>')
def get_towns(model):
    towns = Car.query.filter_by(model=model).with_entities(Car.town).distinct().all()
    town_list = [town[0] for town in towns]  # Converts to a simple list
    return jsonify(town_list)

# I've tried changing the def name to just getRegions but it breaks the code for some reason
# Handles AJAX request and returns regions for a selected model
@core.route('/get-regions/<model>')
def get_regions(model):
    regions = Car.query.filter_by(model=model).with_entities(Car.region).distinct().all()
    region_list = [region[0] for region in regions]  # Converts to a simple list
    return jsonify(region_list)

@core.route('/carform/<int:car_id>', methods=['GET','POST'])
def carform(car_id):
    car = Car.query.filter_by(carIndex=car_id).first()
    form = PurchaseForm()
    if form.validate_on_submit():
        client = Client(name=form.name.data,
                        surname=form.surname.data,
                        email=form.email.data,
                        phone=form.telephone.data,
                        address=form.address.data,
                        town=form.town.data,
                        postcode=form.postcode.data                        
                    )        
        db.session.add(client)
        db.session.commit() 
        car.client_id = client.id
        db.session.add(car)
        db.session.commit()      
        return redirect(url_for('core.checkout', car_id=car.carIndex))    
    return render_template('carform.html', car=car, form=form)

@core.route('/contact')
def contact():
    return render_template('contact.html')

@core.route('/checkout/<int:car_id>')
def checkout(car_id):
    car = Car.query.get(car_id) 
       
    return render_template('checkout.html', car=car)

@core.route('/create-payment-intent/<car_price>', methods=['GET', 'POST'])
def create_payment(car_price):
    # Convert car_price to an integer
    try:
        data = json.loads(request.data)
        # Create a PaymentIntent with the order amount and currency
        intent = stripe.PaymentIntent.create(
            amount=car_price,
            currency='gbp',
            # In the latest version of the API, specifying the 'automatic_payment_methods' parameter is optional because Stripe enables its functionality by default.
            automatic_payment_methods={
                'enabled': True,
            },
        )
        return jsonify({
            'clientSecret': intent['client_secret']
        })
    except Exception as e:
        return jsonify(error=str(e)), 403

galacticMotors/user/views.py
from flask import render_template, request, Blueprint, session, redirect, url_for, flash
from galacticMotors.models import db, Car, Client, User
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user

# Creates blueprint for admin
users = Blueprint('users', __name__)

@users.route("/login", methods=['GET','POST'])
def login():
    # Creates new admin user with name admin1 and hashed password admin123
    # they're this to make it easy to remember while presenting
    # the code is hashed as you only need to run the code once
    #name = 'admin1'
    #password = 'admin123'
    #newuser = User(name=name, password=generate_password_hash(password, method='pbkdf2'))
    # Adds the new user to the database
    #db.session.add(newuser)
    #db.session.commit()
    # Gathers entered name and password 
    name = request.form.get('name')
    password = request.form.get('password')
    # Filters User database to find the user name
    user = User.query.filter_by(name=name).first()
    # Checks if user with that name or password was found
    if not user or not check_password_hash(user.password, password):  
        if request.method == 'POST':      
            flash('Please check your login details and try again.')
        return render_template('login.html') # if the user doesn't exist or password is wrong, reloads the page
    # Grabs logged user id
    login_user(user)
    return redirect(url_for('admin.index'))

@users.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('core.index'))

galacticMotors/templates/base.html
<!DOCTYPE html>
<html lan="en" dir="ltr">
    <head>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <link rel="stylesheet" href="../static/style.css">        
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
        <script src="https://kit.fontawesome.com/466749fc41.js" crossorigin="anonymous"></script>
        <script src="https://js.stripe.com/v3/"></script>         
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg", id="topNavigation">
            <div class="container-fluid justify-content-center", id="navigation">
                <a class="navbar-brand mx-4" href="{{ url_for('core.index')}}">
                    <img src="{{ url_for('static', filename='logo.png')}}" alt="logo">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav text-center" id="navbar">
                        <li class="nav-item nav-fill">
                            <a class="nav-link" aria-current="page" href="{{ url_for('core.index')}}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('core.cars')}}">Buy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('core.contact')}}">Contact</a>
                        </li>
                        {% if not current_user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('users.login')}}">Login</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container-fluid" style="width: 80%; padding-top: 5vw; padding-bottom: 1vw;">
            {% block content %}
            {% endblock %}
        </div>
        <footer class="text-center text-lg-start text-muted">
            <section class="mainFooter">
                <div class="container text-center text-md-start ">
                    <div class="row">
                        <div class="col-md-4 col-lg-3 col-xl-3 mt-4 mx-auto mb-md-0 mb-4">
                            <h6 class="text-uppercase fw-bold mb-4">Contact Us</h6>
                            <p><i class="fa-solid fa-map-location-dot me-3"></i> Park Cres, Peterborough PE1 4DZ</p>
                            <p><i class="fa-solid fa-inbox me-3"></i> info@galacticmotors.co.uk</p>
                            <p><i class="fa-solid fa-phone-volume me-3"></i> 01733 214466</p>
                        </div>
                        <div class="col-md-3 col-lg-2 col-xl-2 mt-4 mx-auto mb-4">
                            <h6 class="text-uppercase fw-bold mb-4">
                                Useful car links
                            </h6>
                            <p>
                                <a href="https://www.moneysupermarket.com/car-insurance/" target="_blank" class="text-reset">Insurance</a>
                            </p>
                            <p>
                                <a href="https://jbrcapital.com/" target="_blank" class="text-reset">Finances</a>
                            </p>
                            <p>
                                <a href="https://www.motorpoint.co.uk/stores" target="_blank" class="text-reset">Car sales</a>
                            </p>
                        </div>
                    </div>
                </div>
            </section>
            <div class="p-4" style="background-color: #010431; color: white;">
                ©2024 Galactic Motors. All rights reserved.
            </div>
        </footer>
        <script src="{{ url_for('static', filename='global.js')}}"></script>
    </body>
</html>

galacticMotors/templates/carform.html
{% extends "base.html" %}
{% block title %}
    {{ car.make }} {{ car.model }}
{% endblock %}
{% block content %}
<div class="container-fluid mt-4">
    <div class="row">
        <div class="col-md-9 mt-4 mb-4">            
            <div class="form-horizontal">                    
                <h2 class="text-center">Your Details</h2>
                <h3 class="text-center">Please can you enter your details specified below</h3>
                <form method="POST">
                    {# The hidden_tag that you can see is a CSRF security feature #}
                    {{ form.hidden_tag() }}
                    <div class="row mt-3 mb-3">
                        {{ form.name.label(class="col-2 col-form-label") }}
                        <div class="col-md-10">
                        {{ form.name(class="form-control form-control", placeholder="First name") }}
                        </div>
                    </div>                            
                    <div class="row mt-3 mb-3">
                        {{ form.surname.label(class="col-2 col-form-label") }}
                        <div class="col-md-10">
                        {{ form.surname(class="col-10 form-control form-control", placeholder="Last name") }}
                        </div>
                    </div>                            
                    <div class="row mt-3 mb-3">
                        {{ form.email.label(class="col-2 col-form-label") }}
                        <div class="col-md-10">
                        {{ form.email(class="col-10 form-control form-control", placeholder="Email")}}
                        </div>
                    </div>                            
                    <div class="row mt-3 mb-3">
                        {{ form.telephone.label(class="col-2 col-form-label") }}
                        <div class="col-md-10">
                        {{ form.telephone(class="col-10 form-control form-control", placeholder="Phone number")}}
                        </div>
                    </div>                            
                    <div class="row mt-3 mb-3">
                        {{ form.address.label(class="col-2 col-form-label") }}
                        <div class="col-md-10">
                        {{ form.address(class="col-10 form-control form-control", placeholder="Address")}}
                        </div>
                    </div>                            
                    <div class="row mt-3 mb-3">
                        {{ form.town.label(class="col-2 col-form-label") }}
                        <div class="col-md-10">
                        {{ form.town(class="col-10 form-control form-control", placeholder="Town")}}
                        </div>
                    </div>                            
                    <div class="row mt-3 mb-3">
                        {{ form.postcode.label(class="col-2 col-form-label") }}
                        <div class="col-md-10">
                        {{ form.postcode(class="col-10 form-control form-control", placeholder="Postcode")}}
                        </div>
                    </div>                            
                    <div class="form-group">
                        <button type="button" class="btn btn-secondary float-end" data-bs-toggle="modal" data-bs-target="#myModal">
                            Next
                        </button>
                    </div>
                    <div class="modal" id="myModal">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">                        
                                    <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                                </div>
                                <div class="modal-body">
                                    <h5>Please can you check to confirm that the data that you have provided here is correct to your full understanding.</h5>
                                </div>
                                <div class="modal-footer">                                    
                                    {{ form.submit(class="btn btn-success")}}
                                </div>  
                            </div>
                        </div>
                    </div>
                </form>                    
            </div>            
        </div>        
        <div class="col-lg-3 mt-4 mb-4 text-center">
            <div class="card bg-light"> 
                <img class="card-img-top rounded" src="{{ url_for('static', filename=car.make ~ car.model ~ '.png') }}" alt="{{ car.make }} {{ car.model }}">       
                <div class="card-body">        
                    <h4 class="card-title">{{ car.make }} {{ car.model }}</h4>
                    <p class="card-text">Car Identification Number: {{ car.carIndex }}</p>                       
                    <p class="card-text"><i class="fa-solid fa-city"></i> {{ car.town }}</p>
                    <p class="card-text">Dealer Info: {{ car.dealer }} </p>
                    <p class="card-text">{{ car.telephone }}</p>
                    <h3 class="card-title">£{{ car.price }}</h3>      
                </div>
            </div>  
        </div>
    </div>
</div> 
{% endblock %}

galacticMotors/templates/cars.html
{% extends "base.html" %}
{% block title %}
    Cars
{% endblock %}
{% block content %}
<div class="container-fluid mt-4 carPageAlign">
  <div class="row">
    <div class="col-lg-12 mt-4 mb-4">
        <div class="filters mb-4">
          <h2>Filters</h2>
          {% if filters.make %}<span>Make: {{ filters.make }}</span>{% endif %}
          {% if filters.model %}<span>Model: {{ filters.model }}</span>{% endif %}
          {% if filters.town %}<span>Town: {{ filters.town }}</span>{% endif %}
          {% if filters.region %}<span>Region: {{ filters.region }}</span>{% endif %}
          {% if priceFilters.minPrice %}<span>Min price: {{ priceFilters.minPrice }}</span>{% endif %}
          {% if priceFilters.maxPrice %}<span>Max price: {{ priceFilters.maxPrice }}</span>{% endif %}
          <form method="get" action="{{ url_for('core.clear_filters') }}">
            <button type="submit" class="btn btn-secondary btn-md" id="clearFilter" aria-label="Clear all filters">Clear All Filters</button>
          </form>
        </div>
        <form method="post" action="{{ url_for('core.filtered_cars') }}">
          <div class="col-lg-12 carFilters">
            <div class="col-lg-2">
              <select name="make" class="form-select form-select-lg mb-3", id="makeDropdown" aria-label="Select make">
                <option value="">Select Make</option>
                {% for make in makes %}
                <option value="{{ make[0] }}">{{ make[0] }}</option>
                {% endfor %}
              </select>
            </div>
            <div class="col-lg-2">
              <select name="model" class="form-select form-select-lg mb-3", id="modelDropdown" aria-label="Select model">
                <option value="">Select Model</option>
                {% for model in models %}
                <option value="{{ model[0] }}">{{ model[0] }}</option>
                {% endfor %}
                </select>
            </div>
            <div class="col-lg-2">
              <select name="town" class="form-select form-select-lg mb-3", id="townDropdown" aria-label="Select town">
                <option value="">Select Town</option>
                {% for town in towns %}
                <option value="{{ town[0] }}">{{ town[0] }}</option>
                {% endfor %}
              </select>
            </div>
            <div class="col-lg-2">
              <select name="region" class="form-select form-select-lg mb-3", id="regionDropdown" aria-label="Select region">
                <option value="">Select Region</option>
                {% for region in regions %}
                <option value="{{ region[0] }}">{{ region[0] }}</option>
                {% endfor %}
              </select>
            </div>
          </div>
          <div class="col-lg-4 carFilters">
            <div class="input-group mb-4 col-lg-4">
              <span class="input-group-text">Min £</span>
              <input type="text" name="minPrice" class="form-control form-control-lg" aria-label="Insert min amount" placeholder="min amount">
            </div>
            <div class="input-group mb-4 col-lg-4">
              <span class="input-group-text">Max £</span>
              <input type="text" name="maxPrice" class="form-control form-control-lg" aria-label="Insert max amount" placeholder="max amount">
            </div>
          </div>
          <div class="col-lg-12">
            <button type="submit" class="btn btn-secondary btn-md" id="applyFilter" aria-label="Apply filters">Apply the Selected Filters</button>
          </div>
        </form>
    </div>
  
    <div class="col-lg-8 mt-4 mb-4 text-center">
      <h2>Results</h2>
      {% for car in cars.items %}
      <div class="card flex-row bg-light">        
        <div class="card-body">
          <div class="block"><img class="float-start img-fluid object-fit-scale border rounded" src="{{ url_for('static', filename=car.make ~ car.model ~ '.png') }}" alt="{{ car.make }} {{ car.model }}"></div>
          <h4 class="card-title">{{ car.make }}</h4>
          <h5 class="card-subtitle mb-2 text-body-secondary">{{ car.model }}</h5>
          <h6><i class="fa-solid fa-palette"></i> {{ car.colour }} <i class="fa-solid fa fa-tachometer"></i> {{ car.miles }}</h6>
          <h5><i class="fa-solid fa-location-dot"></i> {{ car.town }}</h5>
          <p class="card-text">{{ car.description }}</p>
          <h3 class="card-title">£{{ car.price }}</h3>
          <button type="button" class="btn btn-secondary" id="carButton" aria-label="Click to view more details" data-bs-toggle="modal" data-bs-target="#modal{{ car.carIndex }}">View Details</button>
        </div>
      </div>
        <div class="modal fade" id="modal{{ car.carIndex }}">
          <div class="modal-dialog modal-md">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="float-start text-muted me-4">{{ car.carIndex }}</h5>
                <h4 class="modal-title">{{ car.make }} {{ car.model }}</h4>
                <button type="button" class="btn-close" aria-label="Close modal" data-bs-dismiss="modal"></button>
              </div>
              <div class="modal-body">
                <div class="block"><img class="float-start img-fluid object-fit-scale border rounded" src="{{ url_for('static', filename=car.make ~ car.model ~ '.png') }}" alt="{{ car.make }} {{ car.model }}"></div>
                <div class="mt-4 mb-4">
                  <h5><i class="fa-regular fa-registered"></i> {{car.reg }} <i class="fa-solid fa fa-tachometer"></i> {{ car.miles }}</h5> 
                  <h5><i class="fa-solid fa-palette"></i> {{ car.colour }}</h5>
                  <h6><i class="fa-solid fa-info"></i> {{car.description }}</h6>
                  <h6>Region: {{ car.region }}</h6> 
                  <h6> <i class="fa-solid fa-location-dot"></i> {{ car.town }}</h6> 
                  <h6><i class="fa-solid fa-briefcase"></i> {{ car.dealer }}</h6>
                  <h6><i class="fa-solid fa-phone-volume"></i> {{ car.telephone }}</h6>
                </div>
              </div>
              <div class="modal-footer">
                <h3>£{{ car.price }}</h3>
                <a href="{{ url_for('core.carform', car_id=car.carIndex ) }}" aria-label="Buy this car" class="btn btn-success">Purchase</a>
              </div>              
            </div>
          </div>
        </div> 
        {% endfor %}     
      <nav class="mt-4" aria-label="Page navigation">
        <ul class="pagination justify-content-center">
          {% set route_name = 'core.filtered_cars' if session.get('make') or session.get('model') or session.get('town') or session.get('region') or session.get('minPrice') or session.get('maxPrice') else 'core.cars' %}
          {% if cars.has_prev %}
            <li class="page-item">
              <a class="page-link" href="{{ url_for(route_name, page=cars.prev_num, make=session.get('make'), model=session.get('model'), town=session.get('town'), region=session.get('region'), minPrice=session.get('minPrice'), maxPrice=session.get('maxPrice')) }}">
                <span aria-hidden="true">&laquo;</span>
              </a>
            </li>
          {% endif %}
          {% for page_num in cars.iter_pages() %}
            <li class="page-item {% if page_num == cars.page %}active{% endif %}">
              <a class="page-link" href="{{ url_for(route_name, page=page_num, make=session.get('make'), model=session.get('model'), town=session.get('town'), region=session.get('region'), minPrice=session.get('minPrice'), maxPrice=session.get('maxPrice')) }}">{{ page_num }}</a>
            </li>
          {% endfor %}
          {% if cars.has_next %}
            <li class="page-item">
              <a class="page-link" href="{{ url_for(route_name, page=cars.next_num, make=session.get('make'), model=session.get('model'), town=session.get('town'), region=session.get('region'), minPrice=session.get('minPrice'), maxPrice=session.get('maxPrice')) }}">
                <span aria-hidden="true">&raquo;</span>
              </a>
            </li>
          {% endif %}
        </ul>
      </nav>      
    </div>
  </div>
</div>
{% endblock %}

galacticMotors/templates/contact.html
{% extends "base.html" %}
{% block title %}
Contact
{% endblock %}
{% block content %}
<section class="contact" style="padding-top: 2vw;">
    <div class="container">
        <div class="content">
            <div class="left-side">
                <div class="address details">
                    <i class="fas fa-map-marker-alt"></i>
                    <div class="topic">Address</div>
                    <div class="text-one">Park Cres, Peterborough</div>
                    <div class="text-two">PE1 4DZ</div>
                </div>
                <div class="phone details">
                    <i class="fas fa-phone-alt"></i>
                    <div class="topic">Phone</div>
                    <div class="text-one">01733 214 466</div>
                </div>
                <div class="email details">
                    <i class="fas fa-envelope"></i>
                    <div class="topic">Email</div>
                    <div class="text-one">galacticmotors@gmail.com</div>
                    <div class="text-two">orders.galacticmotors@gmail.com</div>
                </div>
            </div>
            <div class="right-side">
                <div class="topic-text">Send us a message</div>
                    <p>If you have anything you want to inform us of or something has gone wrong with your order, you can send us a message from here. It's our pleasure to help you.</p>
                    <form action="#">
                        <div class="input-box">
                            <input type="text" placeholder="Enter your name">
                        </div>
                        <div class="input-box">
                            <input type="text" placeholder="Enter your email">
                        </div>
                        <div class="input-box message-box">
                            <textarea placeholder="Enter your message"></textarea>
                        </div>
                        <div class="button">
                            <input type="button" value="Send Now" onclick="myFunction()">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="map">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2424.051115466827!2d-0.23240572331479806!3d52.5867690720787!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4877f0e5675fed81%3A0xcf0deaec62fac3d7!2sUniversity%20Centre%20Peterborough!5e0!3m2!1sen!2suk!4v1702085037587!5m2!1sen!2suk" width="700" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
    </div>
    <script>
        function myFunction() {
        var txt;
        confirm("You've Sent a Message!")
        }
    </script>
</section>
{% endblock %}

galacticMotors/templates/layout.html
{% macro menu_links(links=None) %}
  {% if links is none %}{% set links = admin_view.admin.menu_links() %}{% endif %}
  {% for item in links %}
    {% if item.is_accessible() and item.is_visible() %}
      <li>
        <a href="{{ item.get_url() }}">{{ menu_icon(item) }}{{ item.name }}</a>
      </li>
    {% endif %}
  {% endfor %}
{% endmacro %}